# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-josefarro'
    organization: '13021302lol'
    scannerMode: 'MSBuild'
    projectKey: 'josefarro.123'
    projectName: 'record store'


- script: cd Old-Record-Store
          dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

  #have recordstore test proect
  #script: dotnet test
  #displayName: dotnet test
  #workingDirectory: RestaurantReview

- task: SonarCloudAnalyze@1


- task: SonarCloudPublish@1
  displayName: Publish SonarCloud quality gate result
  inputs:
    pollingTimeoutSec: '300'


- task: DotNetCoreCLI@2
  displayName: dotnet publish + zip
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(7b6b20dd-8eaa-42bc-be67-56cb3efa9f4f)'
    appType: 'webApp'
    WebAppName: 'kinkyshaming42069'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

